---
title: "hw4"
author: "Aaron Miller"
format: html
html:
  embed_resources: true
---
```{r}
#| message: false
library(RedditExtractoR)
library(tidytext)
library(tidyverse)
```


# Q1 : Top (Content) Words in Avatar Subreddit
```
top_urls <- find_thread_urls(subreddit = 'Avatar')

top_urls
```

```
tidy_urls <- top_urls %>% 
  select(title, text, url) %>% 
  mutate(id = row_number(), short_title = substr(title, 1, 20)) %>% 
  select(id, short_title, text) %>% 
  unnest_tokens(word, text, token = 'words')

```

```
tidy_urls <- tidy_urls %>% 
  anti_join(get_stopwords())

tidy_urls %>% 
  count(word, sort = TRUE)
```

```
tidy_urls %>% 
  count(word, sort = TRUE) %>% 
  top_n(20, n) %>% 
  ggplot(aes(x=n, y=reorder(word, n)))+
  geom_col(show.legend = FALSE)+
  labs(title = 'Most Frequent Words/Morphemes under r/Avatar',
       x = NULL,
       y = 'count')+
  theme_minimal()
```

```{r}
#| error: false
top_urls <- tibble(json = find_thread_urls('Avatar'))

write_rds(top_urls, 'top_urls.rds')
```


```{r}
top_urls <- read_rds('top_urls.rds')

top_urls %>% 
  unnest_wider(json, names_sep = '_') %>% 
  unnest_wider(json_title, names_sep = '_') %>% 
  select(json_title_1) %>% 
  unnest_tokens(word, json_title_1, token = 'words') %>% 
  anti_join(get_stopwords()) %>% 
  count(word, sort = TRUE) %>% 
  top_n(20, n) %>% 
  ggplot(aes(x=n, y=reorder(word, n)))+
  geom_col(show.legend = FALSE)+
  labs(title = 'Most Frequent Words/Morphemes by u/Iasper',
       x = NULL,
       y = 'count')+
  theme_minimal()
```



#Q2: Comments of a Particular Reddit user
```{r}
#| error: false
user <- tibble(json = get_user_content('Iasper'))

write_rds(user, 'user.rds')

```


```{r}
user <- read_rds('user.rds')


my_comments <- user %>% 
  unnest_wider(json) %>% 
  unnest_wider(comments) %>% 
  select(comment)


user %>% 
  unnest_wider(json) %>% 
  unnest_wider(comments) %>% 
  select(thread_title) %>% 
  unnest_longer(thread_title) %>% 
  unnest_tokens(word, thread_title, token = 'words') %>% 
  anti_join(get_stopwords()) %>% 
  count(word, sort = TRUE) %>% 
  top_n(20, n) %>% 
  ggplot(aes(x=n, y=reorder(word, n)))+
  geom_col(show.legend = FALSE)+
  labs(title = 'Most Frequent Words/Morphemes by u/Iasper in thread_title',
       x = NULL,
       y = 'count')+
  theme_minimal()


user %>%
  unnest_wider(json) %>% 
  unnest_wider(comments) %>% 
  select(comment) %>% 
  unnest_longer(comment) %>% 
  unnest_tokens(word, comment, token = 'words') %>% 
  anti_join(get_stopwords()) %>% 
  count(word, sort = TRUE) %>% 
  top_n(20, n) %>% 
  ggplot(aes(x=n, y=reorder(word, n)))+
  geom_col(show.legend = FALSE)+
  labs(title = 'Most Frequent Words/Morphemes by u/Iasper',
       x = NULL,
       y = 'count')+
  theme_minimal()


#??nat_geo_user 
#str(nat_geo_user[[user]]$about)
```

